name: Build OpenSpeedy (64-bit Cloud)

on:
  workflow_dispatch:

jobs:
  build64:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install visualstudio2022buildtools visualstudio2022-workload-vctools cmake ninja -y
        python -m pip install --upgrade pip
        pip install aqtinstall
        # 安装 Qt 5.15.2 MSVC2019 64-bit
        python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:\Qt
        echo "QT_DIR=C:\Qt\5.15.2\msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "CMAKE_PREFIX_PATH=C:\Qt\5.15.2\msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Build 64-bit
      shell: cmd
      run: |
        echo Building 64-bit...
        call script\initenv.bat
        call script\build64.bat

    - name: Show build output files
      shell: cmd
      run: dir build\CMAKE-64bit-Release\Release\

    - name: Collect artifacts
      shell: cmd
      run: |
        mkdir artifacts
        xcopy build\CMAKE-64bit-Release\Release\*.exe artifacts\ /Y
        xcopy build\CMAKE-64bit-Release\Release\*.dll artifacts\ /Y

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-64bit
        path: artifacts/
