name: Build OpenSpeedy (64-bit Cloud)

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - master

jobs:
  build64:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install visualstudio2022community visualstudio2022buildtools visualstudio2022-workload-vctools cmake ninja -y
        python -m pip install --upgrade pip
        pip install aqtinstall
        # 安装 Qt 6.2.4 - 64 位 MSVC2019
        python -m aqt install-qt windows desktop 6.2.4 win64_msvc2019_64

    - name: Build 64-bit
      shell: cmd
      run: |
        call script\initenv.bat
        call script\build64.bat

    - name: Collect artifacts
      shell: cmd
      run: |
        if not exist "artifacts" mkdir artifacts
        copy "build\CMAKE-64bit-Release\OpenSpeedy.exe" artifacts\
        copy "build\CMAKE-64bit-Release\speedpatch64.dll" artifacts\
        copy "build\CMAKE-64bit-Release\bridge64.exe" artifacts\
        dir artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-64bit-build
        path: artifacts/
