name: Build OpenSpeedy (Cloud Serial Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies for 64-bit
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall
          aqt install-qt windows desktop 6.6.0 msvc2019_64 --modules qt6-base

      - name: Build 64-bit
        shell: cmd
        run: |
          call script\initenv.bat
          call script\build64.bat

      - name: Calculate SHA256 of 64-bit OpenSpeedy.exe
        shell: cmd
        run: |
          CertUtil -hashfile build\CMAKE-64bit-Release\OpenSpeedy.exe SHA256
          for /f "tokens=1,* delims= " %%a in ('CertUtil -hashfile build\CMAKE-64bit-Release\OpenSpeedy.exe SHA256 ^| findstr /v "hash CertUtil"') do echo %%b > sha256.txt
          set /p sha256=<sha256.txt
          echo SHA256 (64-bit OpenSpeedy.exe): %sha256%

      - name: Install dependencies for 32-bit
        run: |
          pip install aqtinstall
          aqt install-qt windows desktop 6.6.0 msvc2019 --modules qt6-base

      - name: Build 32-bit
        shell: cmd
        run: |
          call script\initenv.bat
          call script\build32.bat

      - name: Calculate SHA256 of 32-bit speedpatch32.dll
        shell: cmd
        run: |
          CertUtil -hashfile build\CMAKE-32bit-Release\speedpatch32.dll SHA256
          for /f "tokens=1,* delims= " %%a in ('CertUtil -hashfile build\CMAKE-32bit-Release\speedpatch32.dll SHA256 ^| findstr /v "hash CertUtil"') do echo %%b > sha256.txt
          set /p sha256=<sha256.txt
          echo SHA256 (32-bit speedpatch32.dll): %sha256%

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenSpeedy-artifacts
          path: |
            build\CMAKE-64bit-Release\OpenSpeedy.exe
            build\CMAKE-64bit-Release\speedpatch64.dll
            build\CMAKE-64bit-Release\bridge64.exe
            build\CMAKE-32bit-Release\speedpatch32.dll
            build\CMAKE-32bit-Release\bridge32.exe
