name: Debug Qt Architectures (aqt 3.x)

on:
  workflow_dispatch:

jobs:
  list-qt:
    runs-on: windows-latest
    steps:
    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: List all Qt versions
      run: |
        echo "=== 所有 Qt 版本 ==="
        python -m aqt list-qt-official windows desktop

    - name: List architectures for Qt 6.6.0
      run: |
        echo "=== Qt 6.6.0 架构 ==="
        python -m aqt list-qt-official windows desktop 6.6.0

    - name: List architectures for Qt 6.6.1
      run: |
        echo "=== Qt 6.6.1 架构 ==="
        python -m aqt list-qt-official windows desktop 6.6.1

    - name: List architectures for Qt 6.6.3
      run: |
        echo "=== Qt 6.6.3 架构 ==="
        python -m aqt list-qt-official windows desktop 6.6.3
