name: Debug Qt Architectures

on:
  workflow_dispatch:

jobs:
  list-qt:
    runs-on: windows-latest
    steps:
    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: List all Qt versions and architectures
      run: |
        echo "=== 全部 Qt 版本和架构 ==="
        python -m aqt list-qt windows desktop

    - name: List architectures for Qt 6.6.0
      run: |
        echo "=== Qt 6.6.0 可用架构 ==="
        python -m aqt list-qt windows desktop 6.6.0

    - name: List architectures for Qt 6.6.1
      run: |
        echo "=== Qt 6.6.1 可用架构 ==="
        python -m aqt list-qt windows desktop 6.6.1

    - name: List architectures for Qt 6.6.3
      run: |
        echo "=== Qt 6.6.3 可用架构 ==="
        python -m aqt list-qt windows desktop 6.6.3
